def check(string, sub_str): 
    if (string.find(sub_str) == -1): 
        print("NO") 
    else: 
        print("YES") 


with open('data2.txt','r') as f:
	string=f.read()
            
# sub_str ="AGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGA"
#sub_str="TCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCT"
sub_str="GGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGGGGGGAGGAGCGG"
check(string, sub_str)
